### ISSUE TITLE
Windowns OLE detection seems inacurate

### ISSUE THREAD

**Issue by uded** [Xuanwo/go-locale#19]
My current system setting for Internationalization in the [registry key `HKCU/ControlPanel/International/LocalName`](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc775706(v=ws.10)?redirectedfrom=MSDN) states `pl_PL`, but the library querying the system language via OLE is getting back `en-US` as the language.

The code below seems simpler and gets me the right locale every time:

```go
k, err := registry.OpenKey(registry.CURRENT_USER, `Control Panel\International`, registry.QUERY_VALUE)
if err != nil {
	panic(err)
}
defer k.Close()

locale, _, err := k.GetStringValue("LocaleName")
if err != nil {
	panic(err)
}
log.printf("Detected locale: %s", locale)
```

`LocaleName` will return a full locale string, while `Locale` will match with the current `windows_generated.go` map. Tested on Windows XP/7/8/10. Sorry, I do not have Vista anywhere to test it out.

Alternatively using PowerShell is as reliable:

```go
  cmd := exec.Command("powershell", "Get-Culture | select -exp Name")
  output, err := cmd.Output()
  if err == nil {
    return strings.Trim(string(output), "\r\n"), nil
  }
```

I just believe that querying the registry seems like a _cleaner_ solution.

--- 

Code below is a live one I tested with, output at the end. 

```go
import gloc "github.com/Xuanwo/go-locale"

#[...]
	if locTag, err := gloc.Detect(); err ==nil {
		log.Printf("Detedcted language: %s\n", locTag.String())
		locale = display.Tags(locTag)
	}

	k, err := registry.OpenKey(registry.CURRENT_USER, `Control Panel\International`, registry.QUERY_VALUE)
	if err != nil {
		panic(err)
	}
	defer k.Close()

	print, _, err := k.GetStringValue("LocaleName")
	if err != nil {
		panic(err)
	}
	log.Printf("Language from registry: %s", print)
```

```
2020/08/02 14:52:55 Detedcted language: en-US
2020/08/02 14:52:55 Language from registry: pl-PL
```

My locale is and should be `pl-PL`

**Comment by Xuanwo** [comment]
Fixed in #21
