### ISSUE TITLE
Windows locale detection

### ISSUE THREAD

**Issue by pchampio** [Xuanwo/go-locale#9]
Looking at the windows detector, there is an map used to convert windows uint32 language code to the string representation.

https://github.com/Xuanwo/go-locale/blob/36d835c266487651e7d98fdb9531a95c3eaadc88/locale_windows.go#L14-L28

This map isn't aligned with the content of https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

What happen if I use a system configured from `fr-latin-FR` ?
Does this modules works other language than the one defined in this map ?

I'm looking for an alternative to the fork: https://github.com/cubiest/jibberjabber (the uses of some dependency  is questionable)

**Comment by Xuanwo** [comment]
This map's content is picked from `OSLanguage` at https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-operatingsystem , I will update the whole list today so that it can work on all languages.

**Comment by Xuanwo** [comment]
Maybe we can refer to https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/70feba9f-294e-491e-b6eb-56532684c37f

**Comment by Xuanwo** [comment]
This PR may be work for you!

**Comment by pchampio** [comment]
@Xuanwo Thanks!
